version: "3"

services:
  core:
    container_name: plato
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /start-web.sh
    restart: always
    expose:
      - 8000
    ports:
      - 8800:8000
